language: generic 

sudo: required
services: 
  - docker

before_install:
  - docker build -t idanaroz/docker-react -f Dockerfile.dev . 


script: 
  - docker run  -e CI=true idanaroz/docker-react npm run test