language: generic 

sudo: required
services: 
  - docker

before_install:
  - docker build -t idanaroz/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true idanaroz/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app:  "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-997166264699"
  bucket_path: "docker-react"
  on:
    brach: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY